In [1]:
import numpy as np

In [2]:
# create a 1-dimensional array 
a = np.array([1, 2, 3, 4, 5]) 
print(a) 

[1 2 3 4 5]


In [3]:
# create a 2-dimensional array 
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b) 

[[1 2 3]
 [4 5 6]]


In [4]:
# create an array of zeros 
c = np.zeros((3, 4)) 
print(c) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# create an array of ones 
d = np.ones((2, 2)) 
print(d) 

[[1. 1.]
 [1. 1.]]


In [10]:
#Creates an array with evenly spaced values.
e = np.arange(0, 10, 2)
print(e)

[0 2 4 6 8]


In [17]:
list = [1, 2, 3, 4, 5]
array = np.array(list)
s=array.shape
print(s)

(5,)


In [18]:
 # Number of elements in the array
size = array.size  
print(size)

5


In [19]:
 # Data type of the elements in the array
dtype =array.dtype     
print(dtype)

int32


In [6]:
# add two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = a + b 
print(c) 

[5 7 9]


In [20]:
# Subtraction of two arrays
sub=a-b
print(sub)

[-3 -3 -3]


In [21]:
# Division of two arrays
div=a/b
print(div)

[0.25 0.4  0.5 ]


In [7]:
# multiply two arrays 
d = np.array([[1, 2], [3, 4]]) 
e = np.array([[5, 6], [7, 8]]) 
f = d * e 
print(f) 

[[ 5 12]
 [21 32]]


In [8]:
# perform matrix multiplication 
g = np.array([[1, 2], [3, 4]]) 
h = np.array([[5, 6], [7, 8]]) 
i = np.dot(g, h) 
print(i) 

[[19 22]
 [43 50]]


In [22]:
# Square root of each element
a1 = np.array([1, 2, 3, 4, 5])
sqrt_result = np.sqrt(a1)
print(sqrt_result)


[1.         1.41421356 1.73205081 2.         2.23606798]


In [23]:
# Sum of all elements
sum_value = np.sum(a1)
print(sum_value)

15


In [24]:
# Mean of all elements
mean_value = np.mean(a1)
print(mean_value)

3.0


In [27]:
# Median of all elements
median_value = np.median(a1)
print(median_value)

3.0


In [29]:
# Maximum value
max_value = np.max(a1) 
print(max_value)


5


In [30]:
# Minimum value
min_value = np.min(a1)
print(min_value)

1


In [31]:
 # Sort in ascending order and descending order
arr = np.array([3, 1, 2, 4, 5])
sorted_asc = np.sort(arr)
print("ascending order:",sorted_asc)
sorted_desc = np.sort(arr)[::-1] 
print("descending order:",sorted_desc)

ascending order: [1 2 3 4 5]
descending order: [5 4 3 2 1]


In [40]:
# Absolute values
a2 = np.array([-1.5, 2.6, -3.7])
absolute_values = np.abs(a2)
print(absolute_values)

[1.5 2.6 3.7]


In [41]:
# Round to a specified number of decimal places
rounded_values = np.round(a2, 1)
print(rounded_values)

[-1.5  2.6 -3.7]


In [45]:
# Round down to the nearest integer
floor_values = np.floor(a2)
print(floor_values)

[-2.  2. -4.]


In [47]:
# Round up to the nearest integer
ceil_values = np.ceil(a2)
print(ceil_values)

[-1.  3. -3.]
